steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -f
      - infrastructure/docker/Dockerfile.benchmark-runner
      - --build-arg
      - TM_SOURCE_COMMIT=${_SOURCE_COMMIT}
      - -t
      - us-central1-docker.pkg.dev/elite-crossbar-505104-t9/truemandate/benchmark-runner:readiness-fix-${_SOURCE_COMMIT}
      - .
images:
  - us-central1-docker.pkg.dev/elite-crossbar-505104-t9/truemandate/benchmark-runner:readiness-fix-${_SOURCE_COMMIT}
timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
substitutions:
  _SOURCE_COMMIT: unset
