import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * The PUBLIC Agent Card static asset (served at
 * /.well-known/agent-card.json by the web surface) must be a valid A2A 1.0
 * card pointing at the deployed authenticated A2A service, embedding no
 * credentials and staying under the 10 KB registry limit. Generated by
 * scripts/demo/build-agent-card-static.mjs from the SAME builder the
 * deployed A2A service uses (byte-identical by construction).
 */
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const CARD_PATH = path.join(ROOT, "apps/web/public/.well-known/agent-card.json");

describe("public Agent Card static asset", () => {
  const card = JSON.parse(readFileSync(CARD_PATH, "utf8"));

  it("is a valid A2A 1.0 card", () => {
    expect(card.name.length).toBeGreaterThan(0);
    expect(card.description.length).toBeGreaterThan(0);
    expect(card.supportedInterfaces).toHaveLength(1);
    expect(card.supportedInterfaces[0]).toMatchObject({
      url: "https://tm-dev-adk-a2a-o2sz2wgoma-uc.a.run.app/a2a",
      protocolBinding: "JSONRPC",
      protocolVersion: "1.0", // protocol version, never the package version
    });
    expect(card.capabilities).toBeDefined();
    expect(card.skills.map((s: { id: string }) => s.id).sort()).toEqual([
      "canonical-proof",
      "intent-record",
    ]);
  });

  it("names the platform and serializes the security scheme in the canonical wire shape", () => {
    expect(card.name).toBe("TrueMandate Governance Agent");
    const raw = readFileSync(CARD_PATH, "utf8");
    // Direct oneof member name — never the internal $case wrapper.
    expect(raw).toContain("httpAuthSecurityScheme");
    expect(raw).not.toContain("$case");
    expect(raw).toContain('"scheme": "Bearer"');
    expect(raw).toContain('"bearerFormat": "JWT"');
    expect(raw).toContain("run.invoker");
    expect(raw).toContain("No allUsers");
    expect(raw).toContain('"cloudRunIdentity": {');
    expect(raw).toContain('"list": []');
    expect(raw).not.toContain("oauth2");
    expect(raw).not.toContain("openIdConnect");
  });

  it("is under 10 KB and embeds no credentials", () => {
    const raw = readFileSync(CARD_PATH, "utf8");
    expect(raw.length).toBeLessThan(10 * 1024);
    expect(raw).not.toContain("GEMINI_API_KEY");
    expect(raw).not.toContain("private_key");
    expect(raw).not.toContain("service_account");
    expect(raw).not.toContain("-----BEGIN");
    expect(raw).not.toContain("credentials.json");
  });

  it("advertises no economic capability", () => {
    const raw = readFileSync(CARD_PATH, "utf8").toLowerCase();
    expect(raw).not.toContain("payment");
    expect(raw).not.toContain("execute_payment");
    expect(raw).not.toContain("purchase");
  });
});
