/**
 * Stable structured error codes for fail-closed privileged operations.
 * Codes are part of the protocol surface and must remain stable across versions.
 */
export const ErrorCode = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RAW_INTENT_IMMUTABLE: "RAW_INTENT_IMMUTABLE",
  CHILD_AUTHORITY_EXCEEDS_PARENT: "CHILD_AUTHORITY_EXCEEDS_PARENT",
  UNTRUSTED_CANNOT_CREATE_AUTHORITY: "UNTRUSTED_CANNOT_CREATE_AUTHORITY",
  TAINT_ERASURE_FORBIDDEN: "TAINT_ERASURE_FORBIDDEN",
  CRITICAL_CONSTRAINT_MISSING: "CRITICAL_CONSTRAINT_MISSING",
  GRANT_EXPIRED: "GRANT_EXPIRED",
  GRANT_CONSUMED: "GRANT_CONSUMED",
  GRANT_REVOKED: "GRANT_REVOKED",
  GRANT_INTENT_STATE_MISMATCH: "GRANT_INTENT_STATE_MISMATCH",
  /** The authoritative IntentState tip has not been finalized yet. */
  INTENT_STATE_NOT_READY: "INTENT_STATE_NOT_READY",
  PAYMENT_CANNOT_SATISFY_OUTCOME: "PAYMENT_CANNOT_SATISFY_OUTCOME",
  RESOLUTION_REQUIRES_INDEPENDENT_AUTHORITY: "RESOLUTION_REQUIRES_INDEPENDENT_AUTHORITY",
  LEARNING_CANNOT_REWRITE_INTENT: "LEARNING_CANNOT_REWRITE_INTENT",
  LEARNING_PROPOSAL_NOT_PENDING: "LEARNING_PROPOSAL_NOT_PENDING",
  LEARNING_PROPOSAL_EXPIRED: "LEARNING_PROPOSAL_EXPIRED",
  /** INV_026: reputation/trust must never override sticky policy / hard constraints / authority restrictions. */
  REPUTATION_CANNOT_OVERRIDE_POLICY: "REPUTATION_CANNOT_OVERRIDE_POLICY",
  /** INV_027: preference subjectId must match verified caller / demo session identity. */
  PREFERENCE_SUBJECT_MISMATCH: "PREFERENCE_SUBJECT_MISMATCH",
  /** INV_027: preference must not target protected or sticky concepts. */
  PREFERENCE_PROTECTED_CONCEPT: "PREFERENCE_PROTECTED_CONCEPT",
  /** INV_028: workflow-rule subjectId must match verified caller / demo session. */
  WORKFLOW_RULE_SUBJECT_MISMATCH: "WORKFLOW_RULE_SUBJECT_MISMATCH",
  /** INV_028: workflow rule must not target protected concepts. */
  WORKFLOW_RULE_PROTECTED_CONCEPT: "WORKFLOW_RULE_PROTECTED_CONCEPT",
  /** INV_028: reusable workflow rule requires repeated distinct confirmed evidence. */
  WORKFLOW_RULE_INSUFFICIENT_EVIDENCE: "WORKFLOW_RULE_INSUFFICIENT_EVIDENCE",
  PRIVILEGED_PATH_INCOMPLETE: "PRIVILEGED_PATH_INCOMPLETE",
  PROVENANCE_NOT_RECONSTRUCTABLE: "PROVENANCE_NOT_RECONSTRUCTABLE",
  CUMULATIVE_EXPOSURE_EXCEEDED: "CUMULATIVE_EXPOSURE_EXCEEDED",
  CRITICAL_FAILURE_CANNOT_EXPAND_AUTHORITY: "CRITICAL_FAILURE_CANNOT_EXPAND_AUTHORITY",
  PREPARED_ACTION_REQUIRED: "PREPARED_ACTION_REQUIRED",
  PREPARED_ACTION_IMMUTABLE: "PREPARED_ACTION_IMMUTABLE",
  PREPARED_ACTION_HASH_MISMATCH: "PREPARED_ACTION_HASH_MISMATCH",
  PREPARED_ACTION_STALE: "PREPARED_ACTION_STALE",
  COMMIT_TOKEN_EXPIRED: "COMMIT_TOKEN_EXPIRED",
  COMMIT_TOKEN_CONSUMED: "COMMIT_TOKEN_CONSUMED",
  UNKNOWN_EXECUTION_CANNOT_RETRY: "UNKNOWN_EXECUTION_CANNOT_RETRY",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  COMPENSATION_REQUIRES_INDEPENDENT_AUTHORITY:
    "COMPENSATION_REQUIRES_INDEPENDENT_AUTHORITY",
  BUNDLE_CONSTRAINTS_UNMET: "BUNDLE_CONSTRAINTS_UNMET",
  NONCE_REPLAY: "NONCE_REPLAY",
  AUTHORITY_BLOCKED: "AUTHORITY_BLOCKED",
  SCHEMA_PARSE_FAILED: "SCHEMA_PARSE_FAILED",
  /** Model generated output failed the required structured schema (retryable). */
  MODEL_OUTPUT_INVALID: "MODEL_OUTPUT_INVALID",
  GROUNDING_FAILED: "GROUNDING_FAILED",
  NEGATION_LOSS: "NEGATION_LOSS",
  QUANTITY_MISMATCH: "QUANTITY_MISMATCH",
  TEMPORAL_MISMATCH: "TEMPORAL_MISMATCH",
  INVENTED_CONSTRAINT: "INVENTED_CONSTRAINT",
  SEMANTIC_WEAKENING: "SEMANTIC_WEAKENING",
  SEMANTIC_STRENGTHENING: "SEMANTIC_STRENGTHENING",
  MODEL_UNAVAILABLE: "MODEL_UNAVAILABLE",
  SEMANTIC_VERIFICATION_FAILED: "SEMANTIC_VERIFICATION_FAILED",
  PLAN_COVERAGE_GAP: "PLAN_COVERAGE_GAP",
  PLAN_STALE: "PLAN_STALE",
  PROOF_OBLIGATION_MISSING: "PROOF_OBLIGATION_MISSING",
  UNSUPPORTED_OPERATIONALIZATION: "UNSUPPORTED_OPERATIONALIZATION",
  INAPPROPRIATE_COMMITMENT: "INAPPROPRIATE_COMMITMENT",
  DELEGATION_SCOPE_EXPANDED: "DELEGATION_SCOPE_EXPANDED",
  SEMANTIC_READINESS_INSUFFICIENT: "SEMANTIC_READINESS_INSUFFICIENT",
  CONSTRAINT_DROPPED: "CONSTRAINT_DROPPED",
  PLAN_VERIFICATION_FAILED: "PLAN_VERIFICATION_FAILED",
  GUARDIAN_CRITICAL_FAILURE: "GUARDIAN_CRITICAL_FAILURE",
  GUARDIAN_JUDGE_UNAVAILABLE: "GUARDIAN_JUDGE_UNAVAILABLE",
  GUARDIAN_SCHEMA_PARSE_FAILED: "GUARDIAN_SCHEMA_PARSE_FAILED",
  GUARDIAN_VERDICT_STALE: "GUARDIAN_VERDICT_STALE",
  UNTRUSTED_INFLUENCE: "UNTRUSTED_INFLUENCE",
  UNSUPPORTED_ASSUMPTION: "UNSUPPORTED_ASSUMPTION",
  EVIDENCE_INSUFFICIENT: "EVIDENCE_INSUFFICIENT",
  ACTION_PROPOSAL_MISMATCH: "ACTION_PROPOSAL_MISMATCH",
  TOOL_NOT_VISIBLE: "TOOL_NOT_VISIBLE",
  TOOL_PRIVILEGE_DENIED: "TOOL_PRIVILEGE_DENIED",
  TOOL_UNKNOWN: "TOOL_UNKNOWN",
  COMMIT_TOKEN_MISMATCH: "COMMIT_TOKEN_MISMATCH",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_MISMATCH: "APPROVAL_MISMATCH",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  APPROVAL_NOT_PENDING: "APPROVAL_NOT_PENDING",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  APPROVAL_SUPERSEDED: "APPROVAL_SUPERSEDED",
  APPROVAL_STALE_INTENT_STATE: "APPROVAL_STALE_INTENT_STATE",
  APPROVAL_SCOPE_MISMATCH: "APPROVAL_SCOPE_MISMATCH",
  APPROVAL_FOREIGN_ACTION: "APPROVAL_FOREIGN_ACTION",
  APPROVAL_ALREADY_DECIDED: "APPROVAL_ALREADY_DECIDED",
  SIDE_EFFECT_LEDGER_APPEND_FAILED: "SIDE_EFFECT_LEDGER_APPEND_FAILED",
  RECONCILIATION_REQUIRED: "RECONCILIATION_REQUIRED",
  GUARDIAN_VERDICT_REQUIRED: "GUARDIAN_VERDICT_REQUIRED",
  SEMANTIC_GATE_BLOCKED: "SEMANTIC_GATE_BLOCKED",
  OUTCOME_CONTRACT_REQUIRED: "OUTCOME_CONTRACT_REQUIRED",
  OUTCOME_CONTRACT_STALE: "OUTCOME_CONTRACT_STALE",
  OUTCOME_TRANSITION_INVALID: "OUTCOME_TRANSITION_INVALID",
  OUTCOME_MUTATION_FORBIDDEN: "OUTCOME_MUTATION_FORBIDDEN",
  EVIDENCE_STALE: "EVIDENCE_STALE",
  EVIDENCE_NOT_INDEPENDENT: "EVIDENCE_NOT_INDEPENDENT",
  EVIDENCE_CONFLICT: "EVIDENCE_CONFLICT",
  RESOLUTION_TRANSITION_INVALID: "RESOLUTION_TRANSITION_INVALID",
  RESOLUTION_TRIGGER_DUPLICATE: "RESOLUTION_TRIGGER_DUPLICATE",
  RESOLUTION_RECURSION_LIMIT: "RESOLUTION_RECURSION_LIMIT",
  RESOLUTION_EVIDENCE_LIMIT: "RESOLUTION_EVIDENCE_LIMIT",
  RESOLUTION_AGENT_MUTATION_FORBIDDEN: "RESOLUTION_AGENT_MUTATION_FORBIDDEN",
  RESOLUTION_BOUNDS_EXCEEDED: "RESOLUTION_BOUNDS_EXCEEDED",
  REMEDIATION_MANDATE_REQUIRED: "REMEDIATION_MANDATE_REQUIRED",
  REMEDIATION_MANDATE_INVALID: "REMEDIATION_MANDATE_INVALID",
  REMEDIATION_MANDATE_STALE: "REMEDIATION_MANDATE_STALE",
  REMEDIATION_MANDATE_SCOPE: "REMEDIATION_MANDATE_SCOPE",
  REMEDIATION_MANDATE_CASE_MISMATCH: "REMEDIATION_MANDATE_CASE_MISMATCH",
  REMEDIATION_MANDATE_NOT_EXECUTABLE: "REMEDIATION_MANDATE_NOT_EXECUTABLE",
  /** Wave 4.3: MonitoringContract is FROZEN / RESOLUTION_OPENED / CLOSED — no further privileged mint. */
  MONITORING_CONTRACT_FROZEN: "MONITORING_CONTRACT_FROZEN",
  /** Wave 4.3: MonitoringContract escalated — subsequent privileged mint requires approval. */
  MONITORING_ESCALATION_REQUIRES_APPROVAL: "MONITORING_ESCALATION_REQUIRES_APPROVAL",
  /** Wave 4.3: illegal MonitoringContract state transition. */
  MONITORING_TRANSITION_INVALID: "MONITORING_TRANSITION_INVALID",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface StructuredError {
  readonly ok: false;
  readonly code: ErrorCode;
  readonly message: string;
  readonly details?: Readonly<Record<string, unknown>>;
}

export interface OkResult<T = void> {
  readonly ok: true;
  readonly value: T;
}

export type Result<T = void> = OkResult<T> | StructuredError;

export function ok(): OkResult<void>;
export function ok<T>(value: T): OkResult<T>;
export function ok<T>(value?: T): OkResult<T | void> {
  if (arguments.length === 0) {
    return { ok: true, value: undefined };
  }
  return { ok: true, value: value as T };
}

export function err(
  code: ErrorCode,
  message: string,
  details?: Readonly<Record<string, unknown>>,
): StructuredError {
  return details === undefined
    ? { ok: false, code, message }
    : { ok: false, code, message, details };
}
